name: ci-workflow

on:
  push:
    branches: ['**']

jobs:
  build:
    name: Build & Validate
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache:  'npm'

      - name: Install dependencies
        run:  npm ci

      - name: Lint (only if lint script exists)
        run:  |
          if npm run | grep -q " lint"; then
            npm run lint
          else
            echo "No lint script found in package.json - skipping."
          fi

      - name: Build
        run:  npm run build

  security-scan:
    name: Trivy Vulnerability scan
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          format: 'table'
          trivy-version: 'v0.68.2'
